# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 吴俊贤的个人博客
email: wu812730157@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  华南理工大学大三程序猿一只
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://namespacewjx.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  namespacewjx
repository: namespacewjx/namespacewjx.github.io
JEYLLY_GITHUB_TOKEN: 3ad0ed274c1f16d81864cb5977ed6a40a2d0c72b

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
gems:
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - github token.txt
  - cacert.pem
# Global Variables
excerpt_separator: <!--start-->
show_downloads: false

